# Generated by Django 3.2.16 on 2023-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OzonSettingStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='images/')),
                ('login_background', models.ImageField(upload_to='images/')),
                ('primary_color', models.CharField(max_length=256)),
                ('fav_icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='RegionList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
