# Generated by Django 3.2.16 on 2023-07-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='images/')),
                ('login_background', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
